export const CartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN', 
    ADD_ITEM: 'ADD_ITEM', 
    DELETE_ITEM_ROW_FROM_CART: 'DELETE_ITEM_ROW_FROM_CART', 
    DELETE_ITEM: 'DELETE_ITEM'
}